# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Hallo. Ich bin Marc Altmann."
email: 'marcaltmann@posteo.de'
description: "Ich bin Software-Entwickler aus Berlin und entwickle tolle Sachen."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jamigibbs.github.io/phantom" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ''
github_username: 'marcaltmann'
medium_username: ''

# Build settings
markdown: kramdown
# theme: phantom # Uncomment once published to RubyGems
plugins:
  - jekyll-paginate

### Phantom settings
paginate: 10
footer_text: '© 2019 Marc Altmann'
admin_name: 'Marc Altmann'
google_analytics: "UA-9999999-99" # Update with your own tracking ID
enable_contact: true

#### Phantom Navigation menu
enable_nav: false
nav_item:
  - { url: '/', text: 'Home' }
  - { url: '/about', text: 'About' }
